config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :show] do
    collection do
      get :top
    end
    member do
      post :upvote
    end
  end

  resources :users, only: [:show]

  resource :session, only: [:new] do
    collection do
      post :login
      get :logout
    end
  end

  resources :categories, only: [:show]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true

  has_many :posts

end

app/models/comment_comment.rb
class CommentComment < ApplicationRecord

  validates :content, presence: true
  validates :created_by, presence: true

  belongs_to :user, foreign_key: :created_by, primary_key: :nickname
  belongs_to :post_comment

end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :content, presence: true
  validates :created_by, presence: true

  belongs_to :user, foreign_key: :created_by, primary_key: :nickname
  belongs_to :category

  has_many :post_comments, dependent: :destroy

  def upvote!
    self.update!(upvotes: self.upvotes + 1)
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  validates :content, presence: true
  validates :created_by, presence: true

  belongs_to :user, foreign_key: :created_by, primary_key: :nickname
  belongs_to :post

  has_many :comment_comments

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :full_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :nickname, presence: true, uniqueness: true

  has_many :posts, foreign_key: :created_by, primary_key: :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Do not validate the Authenticity Token so that we can perform tests
  # using the ab tool
  skip_forgery_protection if: :testing_without_auth_token

  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user

  private

  def testing_without_auth_token
    Rails.env.development? && params[:test_no_auth_token]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.friendly.find(params[:id])
    @posts = @category.posts.order('created_at desc').limit(100)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post
      .all
      .order('created_at desc')
      .limit(100)
  end

  def top
    # TODO: Only show the top posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def upvote
    post = Post.find(params[:id])
    post.upvote!

    redirect_to post
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def login
    user = User.where("email = '#{params[:email]}'").first
    if user && user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to posts_url, notice: "Logged in as #{user.email}."
    else
      flash[:error] = "Invalid credentials. Try again."
      render :new
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to posts_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/show.html.erb
<h1>Newest Posts in <%= @category.name %></h1>

<% @posts.each do |post| %>
  <p class="post">
    <%= link_to post.title, post %>
    posted by
    <%= link_to post.created_by, post.user %>
    <small>(<%= distance_of_time_in_words(post.created_at, Time.now) %> ago)</small>
    - <%= post.post_comments.count %> comments
    - <%= post.upvotes %> points
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the Animikii Forum</h1>

<p>
Please <%= link_to "log in" %> or <%= link_to "sign up" %> to join the community.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimikiiForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div style="display: inline-block; width: 60%;">
        <%= link_to "Recent Posts", posts_url %> |
        <%= link_to "Top Posts", top_posts_url %> | --- | 
        <% Category.all.limit(4).each do |category| %>
          <%= link_to category.name, category %> |
        <% end %>
      </div>
      <div style="display: inline-block; width: 30%; text-align: right;">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log out", logout_session_path %>
        <% else %>
          <%= link_to "Log in", new_session_path %>
        <% end %>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div style="color: green">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div style="color: red">
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Newest Posts</h1>

<% @posts.each do |post| %>
  <p class="post">
    <%= link_to post.title, post %>
    posted by
    <%= link_to post.created_by, post.user %>
    <small>(<%= distance_of_time_in_words(post.created_at, Time.now) %> ago)</small>
    in <%= link_to post.category.name, post.category %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= link_to @post.category.name, @post.category %> > <%= @post.title %></h1>

<p>
   <%= @post.upvotes %> points. <%= link_to "Upvote", upvote_post_path(@post), method: :post %>
</p>
<p>
Initially posted by <%= @post.created_by %> on
<%= @post.created_at.to_s(:short) %>.

<p class="top-comment">
  <%= @post.content %>
</p>

<% @post.post_comments.order('created_at desc').each_with_index do |comment, index| %>
  <p class="comment <%= index % 2 == 0 ? 'even' : 'odd' %>">
  On <%= comment.created_at.to_s(:short) %> <strong><%= comment.created_by %></strong> wrote: </br>
    <%= comment.content %>
    <% if comment.comment_comments.count > 0 %>
      <% comment.comment_comments.order('created_at desc').each_with_index do |child_comment| %>
        <div style="margin-left: 30px">
          <p class="comment <%= index % 2 == 0 ? 'even' : 'odd' %>">
          <%= link_to child_comment.created_by, child_comment.user %> wrote: 
          <%= child_comment.content %>
          </p>
        </div>
      <% end %>
    <% end %>
  </p>
<% end %>

app/views/posts/top.html.erb
<h1>Top Posts</h1>

<p>Here you can see the most popular posts by upvote for all categories</p>

app/views/users/show.html.erb
<h1><%= User.find(params[:id]).nickname %>'s Posts</h1>

<p>Total points: </p>

<div>
  <%- User.find(params[:id]).posts.order('created_at DESC').limit(50).each do |post| %>
    <div class="post">
      <%= link_to post.title, post %>
    </div>
  <% end %>
</div>